config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end
  resources :users do
  	resource :relationships, only: [:create, :destroy]
  	get 'follower' => 'relationships#follower'
  	get 'followed' => 'relationships#followed'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  attachment :image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :comment, presence: true, length: { minimum: 2, maximum: 200 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord


	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :follower_user, through: :follower, source: :followed

  has_many :followed, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :followed_user, through: :followed, source: :follower


  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    follower_user.include?(user)
  end


  attachment :profile_image

  validates :name, presence: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    users_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @booknew = Book.new
    @books = Book.order(created_at: :desc).page(params[:page]).reverse_order
    @user = User.find(current_user.id)
  end

  def create
    @booknew = Book.new(book_params)
    @booknew.user_id = current_user.id
    if @booknew.save
      flash[:save] = "You have creatad book successfully."
      redirect_to book_path(@booknew)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render 'index'
    end
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render action: :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @booknew = Book.new
    @book = Book.find(params[:book_id])
    @commentnew = Comment.new
    @comments = @book.comments
  end

  def create
    book = Book.find(params[:book_id])
    @commentnew = Comment.new(comment_params)
    @commentnew.user_id = current_user.id
    @commentnew.book_id = book.id
    @commentnew.save
    redirect_to book_comments_path(book)
  end

  def edit
    @book = Book.find(params[:book_id])
    @comment = Comment.find(params[:id])
    if @comment.user_id == current_user.id
      render action: :edit
    else
      redirect_to books_path
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:comment] = 'You have comment updated user successfully.'
      redirect_to book_comments_path(params[:book_id])
    else
      @book = Book.find(params[:book_id])
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to book_comments_path(params[:book_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_comments_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_comments_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


	def create
		@user = User.find(params[:user_id])
		current_user.follow(params[:user_id])
	end

	def destroy
		@user = User.find(params[:user_id])
		current_user.unfollow(params[:user_id])
	end

	def follower
		user = User.find(params[:user_id])
		@users = user.follower_user
	end

	def followed
		user = User.find(params[:user_id])
		@users = user.followed_user
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @booknew = Book.new
  end

  def show
    @booknew = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render action: :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:updateuser] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>New book</h2>
<h3>aohgo</h3>
<h4>aohgo</h4>
<h5>ogh</h5>
<%= form_for booknew do |f| %>
	<div class="form-group">
		<%= f.label :image %>
		<%= f.attachment_field :image %>
	</div>
	<div class="row form-group">
		<%= f.label :title %><br>
		<%= f.text_field :title, class:'col-xs-12' %>
	</div>
	<div class="row form-group">
		<%= f.label :opinion %><br>
		<%= f.text_area :body, class:'col-xs-12' %>
	</div>
	<div class="row">
		<%= f.submit 'Create Book', class:'btn btn-primary btn-block' %>
	</div>
<% end %>
<h4>ogahoj</h4>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<% if @book.errors.any? %>
   			<p class="error">error!!!!</p>
		<% end %>
		<% if @book.errors.any? %>
		  <div id="error_explanation" class="alert alert-danger">
		    <ul>
		      <% @book.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="col-xs-6 col-xs-offset-3">
			<h1>Editing Book</h1>
			<%= form_for @book do |f| %>
				<div class="form-group row">
					<%= f.label :title %><br>
					<%= f.text_field :title, class:'col-xs-12' %>
				</div>
				<div class="form-group row">
					<%= f.label :opinion %><br>
					<%= f.text_area :body, class:'col-xs-12' %>
				</div>
				<div class="row">
					<%= f.submit 'Update Book', class:'btn btn-primary col-xs-12' %>
				</div>
			<% end %>
			<div class="field">
				<%= link_to 'Show', book_path(@book) %> | <%= link_to 'Back', books_path %>
			</div>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<% if @booknew.errors.any? %>
   			<p class="error">error!!!!</p>
		<% end %>
		<% if @booknew.errors.any? %>
		  <div id="error_explanation" class="alert alert-danger">
		    <ul>
		      <% @booknew.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<div class="col-xs-3">
			<%= render 'users/info', user: @user %>
			<%= render 'new', booknew: @booknew %>
		</div>
		<div class="col-xs-9">
			<h1>Books</h1>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Image</th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
							<% end %>
						</td>
						<td>
							<%= link_to book_comments_path(book) do %>
								<%= attachment_image_tag book, :image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
							<% end %>
						</td>
						<td>
							<%= link_to book_path(book) do %>
								<%= book.title %>
							<% end %>
						</td>
						<td>
							<%= book.body %>
						</td>
					</tr>
				<% end %>
				</tbody>
			 </table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<p class="succes"><%= flash[:save] %></p>
			<p class="succes"><%= flash[:update] %></p>
			<%= render 'users/info', user: @user %>
			<%= render 'new', booknew: @booknew %>
		</div>
		<div class="col-xs-9">
			<h1>Book detail</h1>
			<table class="table">
				<tbody>
					<tr>
						<td>
							<%= link_to user_path(@user) do %>
								<%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %><br>
								<%= @book.user.name %>
							<% end %>
						</td>
						<td>
							<%= @book.title %>
						</td>
						<td>
							<%= @book.body %>
						</td>
					<% if @book.user_id == current_user.id %>
						<td>
							<%= link_to 'Edit', edit_book_path(@book), class:'btn btn-success btn-sm' %>
						</td>
						<td>
							<%= link_to 'Destroy', book_path(@book), class:'btn btn-danger btn-sm', method: :delete, "data-confirm" => "本当に消しますか?" %>
						</td>
					<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/comments/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<% if @comment.errors.any? %>
	   			<p class="error">error!!!!</p>
			<% end %>
			<% if @comment.errors.any? %>
			  <div id="error_explanation" class="alert alert-danger">
			    <ul>
			      <% @comment.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			  </div>
			<% end %>
			<h2>Comment Edit!</h2>
			<%= form_for [@book, @comment] do |f| %>
				<div class="form-group">
					<%= f.label :comment %>
					<%= f.text_area :comment %>
				</div>
				<div class="row">
					<%= f.submit 'Update Comment', class:'btn btn-accesse' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/comments/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<p class="succes"><%= flash[:comment] %></p>
			<%= render 'users/info', user: @user %>
			<%= render 'books/new', booknew: @booknew %>
			<h2>Comment</h2>
			<%= form_for [@book, @commentnew] do |f| %>
				<div class="row form-group">
					<%= f.label :comment %><br>
					<%= f.text_area :comment, class:'col-xs-12' %>
				</div>
				<div class="row">
			 		<%= f.submit 'Create Comment', class:'btn btn-primary btn-block' %>
			 	</div>
			<% end %>
		</div>
		<div class="col-xs-9">
			<h2>Comments!<i class="fas fa-heart"></i></h2>
			<div class="book-image">
				<%= attachment_image_tag @book, :image, :fill, 300, 300, fallback: 'noimage.png', size: '300x300' %>
				<% if @book.favorited_by?(current_user) %>
				<li class="favorite-list">
				  <%= link_to book_favorites_path(@book), method: :delete do %>
				    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				    <%= @book.favorites.count %> いいねを取り消す
				  <% end %>
				</li>
				<% else %>
				<li class="favorite-list">
				  <%= link_to book_favorites_path(@book), method: :post do %>
				    <i class="fa fa-heart-o" aria-hidden="true"></i>
				    <%= @book.favorites.count %> いいね
				  <% end %>
				</li>
				<% end %>
			</div>
				<div class="row">
					<p id="favoriters" class="favorites-logo btn btn-success col-xs-6 col-xs-offset-3">いいねしたユーザー！</p>
			    </div>
				<div class="none-box">
					<div id="favorites-name" class="flex">
						<% @book.favorites.each do |book| %>
							<ul id="favorites-item">
							  <li>ユーザー名:<%= book.user.name %></li>
							  <li>
							  	<%= link_to user_path(book.user) do %>
									<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
								<% end %>
							  </li>
							</ul>
						<% end %>
					</div>
				</div>
			<table class="table">
				<thead>
					<th>Name</th>
					<th>Image</th>
					<th>comment</th>
					<th></th>
					<th></th>
				</thead>
				<tbody>
					<% @comments.each do |comment| %>
						<tr>
							<td>
								<%= comment.user.name %>
							</td>
							<td>
								<%= link_to user_path(comment.user) do %>
									<%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
								<% end %>
							</td>
							<td>
								<%= comment.comment %>
				            </td>
				            <td>
				            	<% if comment.user_id == current_user.id %>
				            		<%= link_to 'Edit', edit_book_comment_path(comment.book, comment), class:'btn btn-success btn-sm' %>
				            	<% end %>
				            </td>
				            <td>
				            	<% if comment.user_id == current_user.id %>
				            		<%= link_to '削除', book_comment_path(comment.book, comment), class:'btn btn-danger btn-sm', method: :delete, "data-confirm" => "本当に消しますか?" %>
				            	<% end %>
				            </td>
						</tr>
		    		<% end %>
				</tbody>
			</table>
			
			<div class="wrap">
			    <ul id="tab-menu" class="clearfix">
			      <li><a href="#tab1" class="tab-active">Image</a></li>
			      <li><a href="#tab2" class="">自己紹介</a></li>
			      <li><a href="#tab3" class="">Email</a></li>
			      <li><a href="#tab4" class="">コメント</a></li>
			    </ul>
			    
			    <div id="tab-contents" class="clearfix">
			        <div id="tab1" class="tab">
				      	<% @comments.each do |comment| %>
					      	<table class="table">
					      		<tbody>
					      			<td>
					      				<p>ユーザー名：<%= comment.user.name %></p>
								        <%= link_to user_path(comment.user) do %>
											<%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
										<% end %>
									</td>
								</tbody>
							</table>
						<% end %>
				    </div>
			        <div id="tab2" class="tab">
			        	<% @comments.each do |comment| %>
					      	<table class="table">
					      		<tbody>
					      			<td>
					      				<p>ユーザー名：<%= comment.user.name %></p>
										<p>自己紹介：<%= comment.user.introduction %></p>
									</td>
								</tbody>
							</table>
						<% end %>
			        </div>

			      　<div id="tab3" class="tab">
			      	    <% @comments.each do |comment| %>
					      	<table class="table">
					      		<tbody>
					      			<td>
					      				<p>ユーザー名：<%= comment.user.name %></p>
										<p>メールアドレス：<%= comment.user.email %></p>
									</td>
								</tbody>
							</table>
						<% end %>
			      　</div>

			        <div id="tab4" class="tab">
			            <% @comments.each do |comment| %>
					      	<table class="table">
					      		<tbody>
					      			<td>
					      				<p>ユーザー名：<%= comment.user.name %></p>
										<p>コメント：<%= comment.comment %></p>
									</td>
								</tbody>
							</table>
						<% end %>
			        </div>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<div class="container">
	<div class="row">
		<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers!</strong></span></h1>
	</div>
</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong> !!</span></h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers,</strong></span></p>
			<p>you can share and exchange your opinions , inpressions , and emotins</p>
			<p>about various books!</p>
			<div class="row">
				<%= link_to 'Log in', new_user_session_path, class:'btn btn-info col-xs-10 col-xs-offset-1' %>
				<%= link_to 'Sign Up', new_user_registration_path, class:'btn btn-success col-xs-10 col-xs-offset-1' %>
			</div>
		</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/18f4d5da3c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <spans class="header-logo">Bookers3</span>
      <ul class="nav navbar-nav navbar-right nav-hover">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id) do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>logout
          <% end %>
        </li>
        <% else %>
          <li>
            <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path do %>
              <span class="glyphicon glyphicon-link" aria-hidden="true"></span>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>login
            <% end %>
          </li>
        <% end %>
      </ul>
      <div id="sp-menu">
        <h2>MENU</h2>
        <ul>
          <li><a href="#">MENU1</a></li>
          <li><a href="#">MENU2</a></li>
          <li><a href="#">MENU3</a></li>
          <li><a href="#">MENU4</a></li>
        </ul>
      </div>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    </header>
    <main>
      <div class="container">
        <p class="succes"><%= notice %></p>
      </div>
      <%= yield %>
      <span class="scroll">
        <a id="scroll-image" href="#">
          <img src="/assets/arrow.png">
        </a>
      </span>
    </main>
    <footer class="container">
      <div class="row">
        <p class="col-xs-offset-9">CopyRight Infratop.inc<p>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/_follow.html.erb
<% if current_user == user %>
	<%= link_to edit_user_path(user) do %>
		<span class="glyphicon glyphicon-wrench btn btn-default col-xs-12" aria-hidden="true"></span>
	<% end %>
<% else %>
	<% if current_user.following?(user) %>
		<%= link_to user_relationships_path(user), method: :delete, remote: true, class: 'btn btn-success' do %>
			フォロー外す
		<% end %>
	<% else %>
		<%= link_to user_relationships_path(user), method: :post, remote: true, class: 'btn btn-primary' do %>
			フォローする
		<% end %>
	<% end %>
<% end %>

app/views/relationships/_followed_count.html.erb
<%= link_to user_followed_path(user) do %>
	<%= user.followed_user.count %>
<% end %>

app/views/relationships/_follower_count.html.erb
<%= link_to user_follower_path(user) do %>
	<%= user.follower_user.count %>
<% end %>

app/views/relationships/create.js.erb
$('#relationship<%= @user.id %>').html("<%= j(render 'relationships/follow', user: @user) %>");
$('.follower-count').html("<%= j(render 'relationships/follower_count', user: @user) %>");
$('.followed-count').html("<%= j(render 'relationships/followed_count', user: @user) %>");

app/views/relationships/destroy.js.erb
$('#relationship<%= @user.id %>').html("<%= j(render 'relationships/follow', user: @user) %>");
$('.follower-count').html("<%= j(render 'relationships/follower_count', user: @user) %>");
$('.followed-count').html("<%= j(render 'relationships/followed_count', user: @user) %>");

app/views/relationships/followed.html.erb
<div>
	<% if @users.count == 0 %>
		フォロワーがいません
	<% else %>
		<% @users.each do |user| %>
			<%= attachment_image_tag user, :profile_image, fallback: 'noimage.jpg', size: '30x30' %>
			<%= user.name %>
		<% end %>
	<% end %>
</div>

app/views/relationships/follower.html.erb
<div>
	<% if @users.count == 0 %>
		フォロー中ユーザーがいません
	<% else %>
		<% @users.each do |user| %>
			<%= attachment_image_tag user, :profile_image, fallback: 'noimage.jpg', size: '30x30' %>
			<%= user.name %>
		<% end %>
	<% end %>
</div>

app/views/users/_info.html.erb
<h2>User info</h2>
<table class="table">
	<tbody>
	  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
		<tr>
			<th>name</th>
			<td><%= user.name %></td>
		</tr>
		<tr>
			<th>introduction</th>
			<td><%= user.introduction %></td>
		</tr>
		<tr>
			<th>フォロワー</th>
			<td class="followed-count">
				<%= render 'relationships/followed_count', user: user %>
			</td>
		</tr>
		<tr>
			<th>フォロー中</th>
			<td class="follower-count">
				<%= render 'relationships/follower_count', user: user %>
			</td>
		</tr>
	</tbody>
</table>
<div class="row" id="relationship<%= user.id %>">
	<%= render 'relationships/follow', user: user %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<% if @user.errors.any? %>
   			<p class="error">error!!!!</p>
		<% end %>
		<% if @user.errors.any? %>
		  <div id="error_explanation" class="alert alert-danger">
		    <ul>
		      <% @user.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
		<h2>User info</h2>
		<%= form_for @user do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="form-group">
			<%= f.label :image %>
			<%= f.attachment_field :profile_image %>
		</div>
		<div class="form-group">
			<%= f.label :introduction %>
			<%= f.text_area :introduction %>
		</div>
		<%= f.submit 'Update User' %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'info', user: @user %>
			<%= render 'books/new', booknew: @booknew %>
		</div>
		<div class="col-xs-9">
			<h1>Users</h1>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td>
							<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
						</td>
						<td>
							<%= user.name %>
						</td>
						<td>
							<%= link_to 'Show', user_path(user) %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<p class="succes"><%= flash[:updateuser] %></p>
			<%= render 'info', user: @user %>
			<%= render 'books/new', booknew: @booknew%>
		</div>
		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: 'noimage.png', size: '60x60' %>
						</td>
						<td>
							<%= link_to book_path(book) do %>
								<%= book.title %>
							<% end %>
						</td>
						<td>
							<%= book.body %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>